### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by chunguGuo** [deepsense-ai/roi-pooling#17]
When I run "from roi_pooling.roi_pooling_ops import roi_pooling" in python with tensorflow-gpu, I got a error:

>>> from roi_pooling.roi_pooling_ops import roi_pooling
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "roi_pooling/roi_pooling_ops.py", line 8, in <module>
    roi_pooling_module = tf.load_op_library(lib_path)
  File "/home/forever/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/forever/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/forever/roi-pooling/roi_pooling/roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

How can I fix it?THANKS.

**Comment by chunguGuo** [comment]
I have fixed it. I changed my tensorflow-gpu_1.4.0 to tensorflow-gpu_1.0.0, then I can import roi_pooling now.

**Comment by WKChung1028** [comment]
@chunguGuo i am trying this ops too. may i know where u placed the unzipped files so it will work?

**Comment by WKChung1028** [comment]
i think i solved it, i moved the roi_pooling files to _python2.7/site-packages_ then cd to there and` make`

**Comment by mhnatiuk** [comment]
It doesn't work for me, I get the same NotFoundError `undefined symbol: _ZTIN10tensorflow8OpKernelE` in tensorflow 1.6.0
I compiled the op successfully using this version, which is also compiled from source
