### ISSUE TITLE
regarding the compiling issue

### ISSUE THREAD

**Issue by huaiyanggongzi** [deepsense-ai/roi-pooling#7]
Hi,  

Thanks for sharing the code.

Because I am working on a public computer node, and have some difficulties of running `python setup install`,

```
running install_lib
creating /tmp/lib/python2.7/site-packages/roi_pooling
error: could not create '/tmp/lib/python2.7/site-packages/roi_pooling': Permission denied
```
As a result, when running the test code like `from roi_pooling.roi_pooling_ops import roi_pooling`, it causes the following error message

```
Traceback (most recent call last):
  File "test_run.py", line 7, in <module>
    from roi_pooling.roi_pooling_ops import roi_pooling
  File "/home/DL-Phase3/roi-pooling-master/roi_pooling/roi_pooling_ops.py", line 8, in <module>
    roi_pooling_module = tf.load_op_library(lib_path)
  File "/tmp/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/DL-Phase3/roi-pooling-master/roi_pooling/roi_pooling.so: cannot open shared object file: No such file or directory

```

Are there any workaround? Thanks.

**Comment by limwenyao** [comment]
Go to the directory where the library is saved i.e. 
`/home/DL-Phase3/roi-pooling-master/roi_pooling/`
Download the missing file `roi_pooling.so` from here
`https://github.com/smallcorgi/Faster-RCNN_TF/blob/6e2a941ac250da668cf93899dbd870cc4d838773/lib/roi_pooling_layer/roi_pooling.so`
and you should be good to go

**Comment by limwenyao** [comment]
Go to the folder `~/roi_pooling` and run `make` in your linux cmd line to generate `roi_pooling.so `

**Comment by djongpo** [comment]
@limwenyao what is the command to run the same?
